#!/usr/bin/env python3
"""Compile long-form bout + HDBSCAN feature tables for offline inspection (scratch).

Writes:
  - ``bout_manifest_long.csv`` — one row per bout (manifest identity + bout scalars)
  - ``prototype_hdbscan_features.csv`` — one row per (stream, seed, raw_syllable_id)
    with the stream-aligned feature vector used by HDBSCAN
  - ``BOUT_MANIFEST_DATA_DICTIONARY.md`` — column definitions + summary-stat constituents

Example::

    uv run python scratch/kpms_ensemble_compare/compile_bout_manifest_table.py \\
        --kpms-root "C:/Users/admin/Documents/work/sack/test2" \\
        --legacy-db "C:/Users/admin/Documents/work/sack/test/vast_results_legacy.h5" \\
        --manifest-path "C:/Users/admin/Documents/work/sack/test2/trial_manifest_kpms_tracking.csv" \\
        --phase-i-dir "C:/Users/admin/Documents/work/sack/test2/behavior_ethogram/phase_i"
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

_SCRATCH_DIR = Path(__file__).resolve().parent
if str(_SCRATCH_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRATCH_DIR))

from behavior_ethogram_phase_i import SEEDS, STREAMS, default_phase_i_out_dir  # noqa: E402
from bout_manifest_lib import (  # noqa: E402
    BOUT_LONG_FIELDS,
    bout_row_to_dict,
    collect_stream_tables,
    load_cluster_lookup,
    prototype_csv_fieldnames,
    prototype_row_to_dict,
)

DATA_DICTIONARY = """# Bout manifest export — data dictionary

Generated by ``compile_bout_manifest_table.py``.

## Files

| File | Grain | Purpose |
|------|-------|---------|
| `bout_manifest_long.csv` | **bout** | Inspect outliers (e.g. 3500-frame ITI freezes) with trial identity |
| `prototype_hdbscan_features.csv` | **(stream, seed, raw_syllable_id)** | HDBSCAN input features + prototype scalars; re-cluster offline |
| `bout_descriptive_stats.json` | cohort summary | Percentiles over bout_manifest_long (from ``bout_descriptive_stats.py``) |

## ``bout_manifest_long.csv`` columns

| Column | Definition |
|--------|------------|
| `stream` | kpMS pose stream (`anatomical`, `blob`, `fused`) |
| `seed` | Model seed (`005`, …) |
| `animal_id`, `session`, `trial` | Manifest trial identity |
| `trial_key` | `{animal_id}/{session}/{trial}` |
| `kpms_recording_key` | Key in ``results_apply.h5`` |
| `raw_syllable_id` | kpMS syllable index (per seed; not cross-seed comparable) |
| `bout_index` | 1-based bout counter within `(seed, trial, raw_syllable_id)` |
| `row_start`, `row_end` | Row slice in aligned kpMS / movement series |
| `bout_frames` | `row_end - row_start` |
| `bout_mean_speed_mps` | Mean legacy spot speed (m/s) over bout rows |
| `bout_mean_abs_dheading` | Mean abs consecutive heading change (rad) |
| `bout_frac_still` | Fraction of bout rows with `is_moving == False` |
| `bout_frac_run` | Fraction of bout rows with trial_state `run` |
| `bout_primary_state` | Modal trial_state label in bout |
| `prototype_T_s` | Resampling length for this syllable: `clip(round(1.5 * median_bout_frames), 8, 30)` |
| `prototype_median_bout_frames` | Median bout length for `(seed, raw_syllable_id)` |
| `prototype_max_bout_frames` | Max bout length for that prototype (flags ITI outliers) |
| `phase_scope` | Frame mask used (`all`, `run`, `iti`) |

## ``prototype_hdbscan_features.csv`` columns

Prototype scalars match ``hdbscan_labels.csv``. Feature layout at ``T_max_stream``:

| Block | `feat_*` indices | Content |
|-------|------------------|---------|
| Speed | `000` … `T_max-1` | Median resampled bout speed curve |
| cos(heading) | `T_max` … `2*T_max-1` | Median resampled heading cos |
| sin(heading) | `2*T_max` … `3*T_max-1` | Median resampled heading sin |

Tail indices `T_s` … `T_max-1` per channel are **padded with that channel's mean** (see ``syllable_speed_cluster.py`` PADDING EXPERIMENT).

HDBSCAN receives **column-wise z-scores** of this matrix across prototypes (not stored here; recompute when experimenting).

| Column | Definition |
|--------|------------|
| `T_s`, `T_max_seed`, `T_max_stream`, `n_pad_dims` | Resampling / padding geometry |
| `n_bouts`, `median_bout_frames`, `max_bout_frames` | Bout inventory for prototype |
| `mean_speed_mps`, `mean_abs_dheading`, `frac_still`, `bout_speed_iqr`, `ambiguous` | Prototype scalars (Phase I sidecars) |
| `cluster_id` | Joined from existing Phase I labels when ``--phase-i-dir`` set; else `-1` |
| `feat_000` … | Stream-aligned padded feature vector |

## ``bout_descriptive_stats.json`` constituents

Each summary block is `{name, n, mean, std, p5, p25, p50, p75, p95, min, max}` over:

| Block | Population |
|-------|------------|
| `bout_frames` | All bout rows |
| `bout_mean_speed_mps` | All bout rows |
| `bout_mean_abs_dheading` | All bout rows |
| `bout_frac_still` | All bout rows |
| `bouts_per_prototype` | Count of bouts per `(seed, raw_syllable_id)` |
| `prototype_bout_speed_iqr` | IQR of per-bout mean speeds per prototype (≥2 bouts) |
| `derived_T_s` | `clip(round(1.5 * median_bout_frames), 8, 30)` per prototype |
| `padding_dims_at_Tmax30` | `3 * (30 - derived_T_s)` hypothetical pad count |
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--kpms-root", type=Path, required=True)
    parser.add_argument("--legacy-db", type=Path, required=True)
    parser.add_argument("--manifest-path", type=Path, required=True)
    parser.add_argument("--out-dir", type=Path, default=None)
    parser.add_argument("--phase-i-dir", type=Path, default=None)
    parser.add_argument("--streams", nargs="*", default=None)
    parser.add_argument("--seeds", nargs="*", default=None)
    parser.add_argument("--phase", choices=("all", "run", "iti"), default="all")
    parser.add_argument("--min-bout-frames", type=int, default=4)
    parser.add_argument("--tracking-h5", type=Path, default=None)
    args = parser.parse_args()

    kpms_root = args.kpms_root.expanduser().resolve()
    out_dir = (
        args.out_dir.expanduser().resolve()
        if args.out_dir
        else (args.phase_i_dir or default_phase_i_out_dir(kpms_root)) / "calibration"
    )
    phase_i_dir = (
        args.phase_i_dir.expanduser().resolve()
        if args.phase_i_dir
        else default_phase_i_out_dir(kpms_root)
    )
    streams = tuple(args.streams) if args.streams else STREAMS
    seeds = tuple(args.seeds) if args.seeds else SEEDS

    all_bouts: list[dict[str, object]] = []
    all_protos: list[dict[str, object]] = []
    stream_t_max = 0
    for stream in streams:
        lookup = load_cluster_lookup(phase_i_dir, stream, args.phase)
        bout_rows, proto_rows, t_max = collect_stream_tables(
            kpms_root=kpms_root,
            legacy_db=args.legacy_db.expanduser().resolve(),
            manifest_path=args.manifest_path.expanduser().resolve(),
            stream=stream,
            seeds=seeds,
            phase=args.phase,
            min_bout_frames=args.min_bout_frames,
            tracking_h5=args.tracking_h5.expanduser().resolve() if args.tracking_h5 else None,
            cluster_lookup=lookup or None,
        )
        stream_t_max = max(stream_t_max, t_max)
        all_bouts.extend(bout_row_to_dict(r) for r in bout_rows)
        all_protos.extend(prototype_row_to_dict(r, t_max=t_max) for r in proto_rows)
        print(f"{stream}: {len(bout_rows)} bouts, {len(proto_rows)} prototypes, T_max_stream={t_max}")

    out_dir.mkdir(parents=True, exist_ok=True)
    bout_path = out_dir / "bout_manifest_long.csv"
    with bout_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=list(BOUT_LONG_FIELDS))
        w.writeheader()
        w.writerows(all_bouts)

    proto_path = out_dir / "prototype_hdbscan_features.csv"
    proto_fields = prototype_csv_fieldnames(stream_t_max)
    with proto_path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.DictWriter(fh, fieldnames=proto_fields)
        w.writeheader()
        w.writerows(all_protos)

    dict_path = out_dir / "BOUT_MANIFEST_DATA_DICTIONARY.md"
    dict_path.write_text(DATA_DICTIONARY, encoding="utf-8")

    outliers = sorted(all_bouts, key=lambda r: int(r["bout_frames"]), reverse=True)[:5]
    meta = {
        "n_bout_rows": len(all_bouts),
        "n_prototype_rows": len(all_protos),
        "streams": list(streams),
        "seeds": list(seeds),
        "phase": args.phase,
        "T_max_stream": stream_t_max,
        "top_bout_frame_outliers": outliers,
    }
    meta_path = out_dir / "bout_manifest_export_meta.json"
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    print(f"Wrote {bout_path}")
    print(f"Wrote {proto_path}")
    print(f"Wrote {dict_path}")
    print(f"Wrote {meta_path}")
    if outliers:
        top = outliers[0]
        print(
            "Longest bout: "
            f"{top['bout_frames']} frames — "
            f"{top['stream']}/seed_{top['seed']} "
            f"{top['trial_key']} syllable {top['raw_syllable_id']} "
            f"(state={top['bout_primary_state']})"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
