from __future__ import annotations

import math

PIPELINE_VERSION = "maze_v0.10"
PROCESSING_DATE_FORMAT = "%Y-%m-%dT%H:%M:%S"

DEFAULT_FPS = 26.7
EPOCH_LENGTH_S = 30.0

DEFAULT_PX_PER_CM = 2.42
EXIT_ZONE_RADIUS_CM = 12.5
QC_EXIT_ZONE_RADIUS_CM = 12.5

CENTER_ZONE_RADIUS_FRACTION = 0.7
CENTER_ZONE_RADIUS_CM = 12.5
CENTER_ENTRY_DEBOUNCE_S = 0.5

MOVEMENT_START_THRESHOLD_M_PER_FRAME = math.sqrt(2) / 150
MOVEMENT_STOP_THRESHOLD_M_PER_FRAME = math.sqrt(2) / 300
MOVEMENT_SPEED_MEDIAN_WINDOW_FRAMES = 3
MOVEMENT_ENTRY_DEBOUNCE_FRAMES = 3
MOVEMENT_EXIT_DEBOUNCE_FRAMES = 3
MIN_MOVEMENT_BOUT_DURATION_S = 0.166
MOVEMENT_INTER_BOUT_INTERVAL_S = 0.166

FILTER_FRAMES_NO_ANIMAL = True
MIN_CONFIDENT_NODES_PER_FRAME = 3
MIN_NODE_CONFIDENCE_THRESHOLD = 0.55
MIN_VALID_FRAME_RUN_LENGTH = 5
MIN_MEAN_CONFIDENCE_PER_FRAME: float | None = None

DETECT_MISTRIAL_BEFORE_PROCESSING = True
MIN_VALID_FRAME_FRACTION = 0.05
MIN_VALID_FRAME_RUN_FOR_MISTRIAL = 15
MIN_TOTAL_MOVEMENT_PX_FOR_MISTRIAL = 42.0

MAX_MOVEMENT_PER_FRAME_CM = 15.0
JUMP_FILTER_LOOKAHEAD_FRAMES = 3

TRACE_INTERPOLATE_NANS = True
TRACE_MAX_GAP_FRAMES = 15
TRACE_INTERPOLATE_LOW_CONF = True
TRACE_CONFIDENCE_THRESHOLD = 0.55
TRACE_APPLY_SMOOTHING = True
TRACE_SMOOTHING_WINDOW = 3

MAX_DWELL_TIME_S = 4.0
DWELL_HEATMAP_BLUR_SIGMA = 4.0
QC_IMAGE_STORE_FORMAT = "raw"
QC_IMAGE_PREVIEW_MAX_DIM = 256

IN_RANGE_POINT_NAME = "in-range"
HYBRID_POINT_NAME = "spot_hybrid"
AMBIULATION_POINT_NAMES = ("spot", "centroid", "in-range", HYBRID_POINT_NAME)


def get_config_snapshot() -> dict:
    """Return a reproducible snapshot of algorithm-facing pipeline settings."""
    return {
        "pipeline_version": PIPELINE_VERSION,
        "default_fps": DEFAULT_FPS,
        "epoch_length_s": EPOCH_LENGTH_S,
        "exit_zone_radius_cm": EXIT_ZONE_RADIUS_CM,
        "movement_start_threshold": MOVEMENT_START_THRESHOLD_M_PER_FRAME,
        "movement_stop_threshold": MOVEMENT_STOP_THRESHOLD_M_PER_FRAME,
        "movement_speed_median_window_frames": MOVEMENT_SPEED_MEDIAN_WINDOW_FRAMES,
        "movement_entry_debounce_frames": MOVEMENT_ENTRY_DEBOUNCE_FRAMES,
        "movement_exit_debounce_frames": MOVEMENT_EXIT_DEBOUNCE_FRAMES,
        "min_movement_bout_duration_s": MIN_MOVEMENT_BOUT_DURATION_S,
        "trace_max_gap_frames": TRACE_MAX_GAP_FRAMES,
        "trace_smoothing_window": TRACE_SMOOTHING_WINDOW,
        "min_confident_nodes_per_frame": MIN_CONFIDENT_NODES_PER_FRAME,
        "min_node_confidence_threshold": MIN_NODE_CONFIDENCE_THRESHOLD,
        "min_mean_confidence_per_frame": MIN_MEAN_CONFIDENCE_PER_FRAME,
    }
